name: build
on: [push]

jobs:
  build:
    name: Runner
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install liburiparser-dev libglib2.0-dev gobject-introspection valac gtk-doc-tools libjson-glib-dev
      - uses: BSFishy/meson-build@v1.0.1
        with:
          action: test
          options: "--wrapper 'valgrind --leak-check=full --error-exitcode=1 --errors-for-leak-kinds=definite"
