name: build
on: [push]

jobs:
  build:
    name: Runner
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install liburiparser-dev libglib2.0-dev gobject-introspection valac libjson-glib-dev meson valgrind
      - name: Run tests
        run: |
          meson build -Ddemo=false -Ddocs=false
          cd build
          meson test --wrapper 'valgrind --leak-check=full --error-exitcode=1 --errors-for-leak-kinds=definite'
